CREATE DATABASE IF NOT EXISTS WebScraper;

USE WebScraper

CREATE TABLE Advertisement (
    id INT NOT NULL AUTO_INCREMENT ,
    district VARCHAR (255) NOT NULL ,
    category VARCHAR (255) NOT NULL ,
    title VARCHAR (255) NOT NULL ,
    description VARCHAR (255) NOT NULL ,
    price VARCHAR (255) NOT NULL ,
    CONSTRAINT PRIMARY KEY (id)
)ENGINE=INNODB;

